Adding group by to the aggregator for the metrics query.
cloudspannerecosystem/autoscaler pull request #100
Opened 2023-03-24 20:59 UTC by bgood

Multi-region Cloud Spanner deployments were over-reporting on metrics in the poller because the metric value for each location was being summed.  For example, if every location was seeing 5% the reported CPU utilization was 15%, this could even cause observed utilization to be greater than 100%.

To resolve this issue a group_by has been added to the aggregator and the maximum metric values is selected across regions. This allows a scaling event to be triggered if a read-only region crosses the threshold, keeping all regions below the utilization threshold.

2023-03-29 07:32 UTC, henrybell requested changes

2023-04-07 17:04 UTC, bgood commented on poller/poller-core/index.js
> +      groupByFields: ['resource.location'],
That is exactly what will happen.

I've added logging per your suggestion, example in the main comments.

2023-04-07 17:06 UTC, bgood commented
The logs will now include location, so we can see what region is causing scaling events for multi-regional deployments

```
----- <project-id>/autoscale-test: Getting Metrics -----
Get max high_priority_cpu from <project-id>/autoscale-test over 5 minutes.
high_priority_cpu = 2.3329512316740555, threshold = 65, margin = 5, location = us-central1
Get max rolling_24_hr from <project-id>/autoscale-test over 5 minutes.
rolling_24_hr = 1.8298442569345388, threshold = 90, margin = 5, location = us-central1
Get max storage from <project-id>/autoscale-test over 5 minutes.
storage = 0, threshold = 75, margin = 5, location = global
----- Published message to topic: projects/<project-id>/topics/scaler-topic
----- <project-id>/multi-region: Getting Metrics -----
Get max high_priority_cpu from <project-id>/multi-region over 5 minutes.
high_priority_cpu = 2.8891162794043446, threshold = 45, margin = 5, location = us-central2
Get max rolling_24_hr from <project-id>/multi-region over 5 minutes.
rolling_24_hr = 0.07862208334233332, threshold = 90, margin = 5, location = us-central1
Get max storage from <project-id>/multi-region over 5 minutes.
storage = 0, threshold = 75, margin = 5, location = global
```

`autoscale-test` is a regional deployment (us-central1)
`multi-region` is a multi-regional deploy (nam10)

2023-04-11 16:36 UTC, henrybell approved these changes
LGTM

2023-04-11 22:05 UTC, merged