feat: Add scaling duration dashboard
cloudspannerecosystem/autoscaler pull request #347
Opened 2024-07-09 13:58 UTC by henrybell

This additionally updates the domain used by the GCP Metrics exporter for the OpenTelemetry collector from  `custom.googleapis.com` to `workload.googleapis.com` (for consistency with the Cloud Functions deployment).

2024-07-09 14:11 UTC, henrybell commented
/gcbrun

2024-07-10 21:06 UTC, nielm approved these changes

2024-07-10 21:08 UTC, nielm commented
Consider changing this to a `feat!` with a BREAKING CHANGE comment, and holding off merging until we decide when to do a cut off to v3.

Reason: if anyone is using the metrics, this will break their existing alerts/dashboards

2024-07-10 21:09 UTC, nielm requested changes
See other comment about changing to a feat!

2024-07-11 12:23 UTC, henrybell commented
Converted to draft pending discussion on when to merge.

2024-07-23 13:18 UTC, nielm approved these changes

2024-07-23 13:20 UTC, merged