Add support for deployment to GKE
cloudspannerecosystem/autoscaler pull request #72
Opened 2022-11-16 16:46 UTC by henrybell

This PR restructures the repository and adds code/config to support deployment of the Autoscaler to Kubernetes (GKE) as well as to Google Cloud Functions, fixing #67. As well as this, #71 and #62 are additionally fixed as a result of changes to the service account provisioning/permissions within the Terraform code.

Because this PR is large and touches a significant proportion of the codebase, thorough testing before merging is recommended -- we can set aside some time for this if helpful.

2022-11-18 22:08 UTC, bgood commented
Thanks for the PR!

I've started working through it, but you are right it is a big one.  One thing we'll need to update are the GitHub Actions to run unit tests. I think the change is simply to update the working directories.

2022-11-22 15:12 UTC, henrybell commented
I fixed the `markdownlinter` findings and modified the paths for the unit tests -- will check the results next time the workflows run (currently waiting for approval). Thanks!

2022-11-29 18:22 UTC, bgood commented
Did a quick run through of the per-project Cloud Functions deployment.  Looks like the working directory exports in the READMEs need to be updated.  Here is an example from the per-project README, `export AUTOSCALER_DIR="$(pwd)/autoscaler/terraform/per-project"`.

- [ ] terraform/cloud-functions/distributed/README.md
- [ ] terraform/cloud-functions/per-project/README.md

2022-12-13 17:09 UTC, bgood requested changes
Looking good. Made a few suggestions around cleaning links in the markdown.

2022-12-13 17:09 UTC, bgood commented on README.md
> +[autoscaler-poller]: poller/README.md
Unused links.

2022-12-13 17:09 UTC, bgood commented on terraform/gke/README.md
> +    Monitoring
Add link back to monitoring section.

2022-12-14 18:44 UTC, henrybell commented on terraform/gke/README.md
> +    export TF_VAR_terraform_spanner_state=true
I have these docs changes made on another branch, will add to the PR once tested.

2022-12-20 19:31 UTC, bgood commented
@davidcueva , this change is looking good.  Given the size and scope would you also be able to do a quick review?

2022-12-22 17:44 UTC, henrybell commented
Closing to recreate from new `master` branch following #75.

2022-12-22 17:44 UTC, closed without merging