Publish Pub/Sub messages when scaling Spanner instances
cloudspannerecosystem/autoscaler pull request #91
Opened 2023-03-05 20:45 UTC by GarupanOjisan

This change introduces a feature that publishes Pub/Sub messages whenever Spanner instances are scaled up/down.
This enables other services to respond to the changes in Spanner capacity.

This feature addresses the following issue.
It allows users to subscribe to the Pub/Sub messages and send notifications to any platforms.

https://github.com/cloudspannerecosystem/autoscaler/issues/12

2023-03-26 16:48 UTC, GarupanOjisan commented
This PR resolves issue #12

2023-07-03 13:14 UTC, henrybell requested changes
I added a couple of comments as well as the two additional commits as discussed:

- [Update working directory to core](https://github.com/cloudspannerecosystem/autoscaler/pull/91/commits/e0a0354cb5d8ea52f7398bdfeaa4870b990476b9)
- [Add 'downstream' identifier to loglines](https://github.com/cloudspannerecosystem/autoscaler/pull/91/commits/2aedb80f6decdaa40e42f8c8a19659d0e0c6b9af)

I tested with Cloud Functions and GKE -- in both cases the downstream messages were successfully sent follow scaling events.

2023-09-09 01:33 UTC, GarupanOjisan commented on poller/poller-core/index.js
> +              'INFO', spanner))
Of course, I didn't consider that fully. We'll keep it.

2023-09-09 01:53 UTC, GarupanOjisan commented on scaler/scaler-core/index.js
> +      await publishDownstreamEvent('SCALING', spanner, suggestedSize);
I would assume that what the user wants to know is the actual success or failure of the scale. At the very least, we need to be able to distinguish between a failure of a publishDownstreamEvent and an actual scale failure.

2023-09-14 06:28 UTC, henrybell approved these changes
LGTM! Many thanks for your work on this PR.

2023-09-14 06:29 UTC, merged